name: Build and test
on:
  push:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/main/java-templates/**/*.java"
      - "src/main/kotlin/**/*.kt"
      - "src/main/resources/config.yml"
      - "src/main/resources/Lobby.zip"
      - "src/main/resources/plugin.yml"
      - "src/main/resources/META-INF/services/"
      - "src/test/java/**/*.java"
      - "src/test/kotlin/**/*.kt"
      - "src/test/resources/"
      - "pom.xml"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
      - "!COPYING"
  pull_request:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/main/java-templates/**/*.java"
      - "src/main/kotlin/**/*.kt"
      - "src/main/resources/config.yml"
      - "src/main/resources/Lobby.zip"
      - "src/main/resources/plugin.yml"
      - "src/main/resources/META-INF/services/"
      - "src/test/java/**/*.java"
      - "src/test/kotlin/**/*.kt"
      - "src/test/resources/"
      - "pom.xml"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
      - "!COPYING"
  workflow_dispatch:


defaults:
  run:
    shell: bash


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm]
        java-version: [8, 11, 17, 21, 25]
    timeout-minutes: 6
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: corretto
          cache: maven

      - uses: dorny/paths-filter@v3.0.2
        id: path-filter
        with:
          filters: |
            parser:
              - "src/main/java/colosseum/construction/parse/*.java"

      - if: ${{ steps.path-filter.outputs.parser == 'true' }}
        run: mvn -B -V -e -ntp -Dstyle.color=always clean verify

      - if: ${{ steps.path-filter.outputs.parser != 'true' }}
        run: set +H && mvn -B -V -e -ntp -Dstyle.color=always -Dtest='!TestMapParseByColosseum' clean verify

      - name: Write test report
        uses: mikepenz/action-junit-report@v5.6.2
        if: ${{ success() || failure() }}
        with:
          report_paths: ./target/surefire-reports/TEST-*.xml
          include_passed: true
          detailed_summary: true
          fail_on_failure: true
          require_tests: true
          check_name: Test Report (${{ matrix.os }}, Java ${{ matrix.java-version }})
          check_title_template: '{{SUITE_NAME}} | {{TEST_NAME}}'

      - name: JaCoCo Code Coverage Report
        uses: NorthRealm/jacoco-csv-summary@v1.1.1
        with:
          csv-file: ./target/jacoco-report/jacoco.csv
          write-summary: true
          write-check: true
          check-name: Code Coverage (${{ matrix.os }}, Java ${{ matrix.java-version }})

      - name: Upload artifacts
        if: ${{ (github.ref_name == 'master' && github.event_name == 'push') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v6
        with:
          name: ConstructionSite-${{ github.run_id }}-${{ matrix.os }}-java-${{ matrix.java-version }}
          path: |
            target/*.jar
            target/jacoco-report
            target/surefire-reports
          retention-days: 1
          overwrite: true
